receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

  memory_limiter:
    limit_mib: 512
    check_interval: 1s
    spike_limit_mib: 128

connectors:
  flowmetrics:
    timeout: 5s

exporters:
  otlp/jaeger:
    endpoint: http://jaeger:4317
    tls:
      insecure: true

  prometheus:
    endpoint: 0.0.0.0:8889
  
  debug:
    verbosity: detailed
    sampling_initial: 2
    sampling_thereafter: 500

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/jaeger, flowmetrics, debug]

    metrics:
      receivers: [flowmetrics]
      processors: []
      exporters: [prometheus, debug]

  telemetry:
    logs:
      level: info
      output_paths: ["stdout"]
    metrics:
      level: detailed