services:
  otel-collector:
    build:
      context: ./otel-collector
      dockerfile: Dockerfile
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
      - "8889:8889"
    volumes:
      - ./otel-collector/collector-config.yaml:/etc/otel-collector-config.yaml:ro

  jaeger:
    image: jaegertracing/all-in-one:1.50
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  prometheus:
    image: prom/prometheus:v2.47.2
    ports:
      - "9090:9090"
      - "24317:4317"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana:10.2.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  shop-orders:
    build:
      context: ../Shop.Orders
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=shop-orders
    depends_on:
      - otel-collector
      - redis

  shop-payments:
    build:
      context: ../Shop.Payments
      dockerfile: Dockerfile
    ports:
      - "5002:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=shop-payments
    depends_on:
      - otel-collector
      - redis

  shop-fulfillment:
    build:
      context: ../Shop.Fulfillment
      dockerfile: Dockerfile
    ports:
      - "5003:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=shop-fulfillment
    depends_on:
      - otel-collector
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"